name: todo_api
description: The interface and models for an API providing access to todos
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.3
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  meta: ^1.9.1
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.1
  freezed: ^2.3.5
  json_serializable: ^6.7.1
