name: todo_list
description: A simple crossplatform ToDo list implementation
version: 1.1.0+2
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dynamic_color: ^1.6.5
  easy_dynamic_theme: ^2.3.1
  easy_localization: ^3.0.2
  logger: ^1.4.0
  intl: ^0.18.1
  shared_preferences: ^2.1.2
  todo_api:
    path: packages/todo_api
  local_storage_todos_api:
    path: packages/local_storage_todos_api
  remote_storage_todos_api:
    path: packages/remote_storage_todos_api
  todo_repository:
    path: packages/todo_repository
  equatable: ^2.0.5
  device_info_plus: ^9.0.2
  uuid: ^3.0.7
  go_router: ^9.0.0
  get_it: ^7.6.0
  connectivity_plus: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
