name: local_storage_todos_api
description: A Flutter implementation of the TodosApi that uses local storage.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
#  isar: ^3.1.0+1
  meta: ^1.7.0
  sqflite: ^2.2.8+4
  todo_api:
    path: ../todo_api

dev_dependencies:
  flutter_lints: ^2.0.1
#  flutter_test:
#    sdk: flutter
#  mocktail: ^0.3.0
