name: todo_repository
description: A repository taht handles requests related to todo's
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  todo_api:
    path: ../todo_api

dev_dependencies:
  flutter_lints: ^2.0.1
  mocktail: ^0.3.0
  test: ^1.19.2

