name: remote_storage_todos_api
description: A Flutter implementation of the TodoApi that uses remote storage.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  todo_api:
    path: ../todo_api
  rxdart: ^0.27.5
  http: ^1.0.0
  envied: ^0.3.0+3

dev_dependencies:
  build_runner: ^2.4.5
  envied_generator: ^0.3.0+3
  flutter_lints: ^2.0.1
